@startuml
skinparam classAttributeIconSize 0
left to right direction

package generator{

    Asm_generator *-- "*" Instrcution

    class Asm_generator{
        -vector<Instruction *> instruction
        -symbolTable : map<string, int>
    }

    
    Ir_generator *-- "*" Instrcution

    class Ir_generator{
        -vector<Instruction *> instruction
        -ast : Node *
        -symbolTable : map<string, int>
        -tempVarCount : int
        -stackOffset : int
    }

}

package ir{

    Instruction --> inst_type

    class Instruction{
        -_op : inst_type
        -_source : string
        -_dest : string
        -_operand : string
    }

    enum inst_type {
        cst
        store
        load
        ret
        add
        su
        mul
        div
    }
}


package ast{

    Statement --|> Node
    Assignement --|> Operator
    Block --|> Node
    Constant --|> Expression
    Operator --|> Expression
    Return --|> Expression
    Variable --|> Expression

    Block *-- "*" Expression
    
    class Node{
        
    }

    class Assignement{
        -lvalue : Variable *
        -rvalue : Expression *
    }
    
    class Block{
        -statement : Expression *
    }
    
    class Constant{
        -value : int
    }
    
    class Operator{
        -left : Expression *
        -right : Expression *
        -op : Operator
    }
    
    Operator --> OpType
    class Operator{
        -opType : OpType
    }
    
    enum OpType {
        MULT
        DIV
        ADD
        MINUS
        ASSIGN
    }

    
    class Return{
        -statement : Expression *
    }
    
    class unExpression{
        -expr : Expression *
        -op : UnOperator
    }
    UnOperator --> UnOpType
    class UnOperator{
        -opType : UnOpType
    }

    enum UnOpType{
        UN_PLUS
        UN_MINUS
    }

    class Expression{
        
    }
    
    class Variable{
        -name : string
    }

}
    
class Visitor{
    -symbolTable : map<string, int>
    -stackOffset : int
    -errorCount : int
}

class main{

}

@enduml