tri: tri.c
    ../compiler/ifcc tri.c
    gcc -no-pie tri.s -o tri

negativityOfNb: negativityOfNb.c
    ../compiler/ifcc negativityOfNb.c
    gcc -no-pie negativityOfNb.s -o negativityOfNb

calculateurBasique: calculateurBasique.c
    ../compiler/ifcc calculateurBasique.c
    gcc -no-pie calculateurBasique.s -o calculateurBasique

clean:
	rm -rf *.s


