tri: tri.c
    ../compiler/ifcc tri.c
    gcc tri.s -o tri

negativityOfNb: negativityOfNb.c
    ../compiler/ifcc negativityOfNb.c
    gcc negativityOfNb.s -o negativityOfNb

calculateurBasique: calculateurBasique.c
    ../compiler/ifcc calculateurBasique.c
    gcc calculateurBasique.s -o calculateurBasique

clean:
	rm -rf *.s


