tri: tri.c
	../compiler/ifcc tri.c
	gcc x86output.s -o tri

neg: negativityOfNb.c
	../compiler/ifcc negativityOfNb.c
	gcc x86output.s -o neg

cal: calculateurBasique.c
	../compiler/ifcc calculateurBasique.c
	gcc x86output.s -o cal

clean:
	rm -rf *.s


